name: GitOps Pipeline

on:
  push:
    branches: [ "main" ]

permissions: write-all

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: login to Dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build with Docker
      uses: docker/build-push-action@v6
      with:
        context: ./weather/
        push: true
        tags: michaelaviram/app:${{ github.run_number }}

    - name: checkout gitops repo
      uses: actions/checkout@v4
      with:
        repository: michaelaviram/argocd
    
    - name: Update version in repo
      uses: mikefarah/yq@master
      with:
        cmd: yq -i '.deployment.image = "michaelaviram/app:${{ github.run_number }}"' 'weatherapp/values.yaml'
    
    - name: push to gitops repo
      run: |
        git config user.name michaelaviram
        git config user.email michael.aviram@gmail.com
        git add weatherapp/values.yaml
        git commit -m "changed version"
        git push https://github.com/michaelaviram/argocd
    




